#!/bin/bash
#
# hg-dude - Mercurial commit notifier
# https://github.com/erjiang/hg-dude
#
# Copyright (C) 2011 Marcin Kulik <http://ku1ik.com/>
#                    Eric Jiang <http://ericjiang.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# Distributed under the GNU General Public License, version 2.0.

interval=$HG_DUDE_INTERVAL
interval=${interval:-60}

export LC_ALL=C # make sure git talks english

[[ -d $1 ]] && cd $1

function notify() {
  if [ $(which notify-send 2>/dev/null) ]; then
    notify-send -i "$1" "$2" "$3"
  elif [ $(which growlnotify 2>/dev/null) ]; then
    growlnotify --image "$1" -m "$3" "$2"
  elif [ $(which kdialog 2>/dev/null) ]; then
    kdialog --icon $1 --title "$2" --passivepopup "$3"
  else
    echo $2; echo $3
  fi
}

while true; do
  for dir_name in *; do
    if [[ -d "$dir_name" && $(cd "$dir_name"; hg identify 2>/dev/null) ]]; then
      repo_name=$dir_name
      cd "$dir_name"

      changes=$(hg incoming --template '{desc} ({author})\n' | sed 's/ <.*>//' | sed '1,2d')

      icon_path=$HG_DUDE_ICON
      icon_path=${icon_path:-`pwd`/icon.png}
      eval icon_path=$icon_path # to expand ~
      if [ "$changes" != "no changes found" ]; then
        notify $icon_path "New commits in $repo_name" "$changes"
        hg pull # :)
      fi

      cd - &>/dev/null
    fi
  done

  sleep $interval
done
